platform :ios, '12.0'

target 'TestSwiftMonkey' do
#  use_frameworks!
  pod 'SwiftMonkeyPaws'
end

target 'TestSwiftMonkeyUITests' do
  pod 'SwiftMonkey', :git => 'https://github.com/zalando/SwiftMonkey.git'
end
